import React from 'react';
import { notFound } from 'next/navigation';
import { getResearchReportBySlug, getAllResearchReports } from '@/lib/research-reports';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import Link from 'next/link';
import { format } from 'date-fns';
import fs from 'fs';
import path from 'path';

interface PageProps {
  params: Promise<{
    slug: string;
  }>;
}

export async function generateStaticParams() {
  const reports = getAllResearchReports();
  return reports.map((report) => ({
    slug: report.slug,
  }));
}

export default async function ResearchReportPage({ params }: PageProps) {
  const { slug } = await params;
  const report = getResearchReportBySlug(slug);

  if (!report || report.status !== 'published') {
    notFound();
  }

  // Read the markdown file
  const markdownPath = path.join(process.cwd(), 'research-report-' + report.slug + '.md');
  const markdownContent = fs.readFileSync(markdownPath, 'utf-8');

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <div className="max-w-4xl mx-auto">
        {/* Back Link */}
        <div className="mb-6">
          <Link
            href="/research"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 font-medium"
          >
            <svg
              className="w-5 h-5 mr-2"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M10 19l-7-7m0 0l7-7m-7 7h18"
              />
            </svg>
            Back to Research Reports
          </Link>
        </div>

        {/* Report Header */}
        <div className="bg-white rounded-lg shadow-md p-8 mb-8">
          <div className="flex items-center gap-3 mb-4">
            <span className="px-3 py-1 bg-blue-100 text-blue-800 text-sm font-medium rounded-full">
              {report.category}
            </span>
            <span className="text-sm text-gray-500">
              {format(new Date(report.date), 'MMMM d, yyyy')}
            </span>
          </div>

          <h1 className="text-3xl font-bold text-gray-900 mb-4">
            {report.title}
          </h1>

          <p className="text-gray-600 mb-6 text-lg leading-relaxed">
            {report.description}
          </p>

          <div className="flex flex-wrap items-center gap-4 text-sm text-gray-500 border-t pt-4">
            <div className="flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
              <span>{report.author}</span>
            </div>
            <div className="flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
              </svg>
              <span>{report.wordCount.toLocaleString()} words</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {report.tags.map((tag) => (
                <span
                  key={tag}
                  className="px-2 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded"
                >
                  #{tag}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Markdown Content */}
        <div className="bg-white rounded-lg shadow-md p-8">
          <article className="prose prose-lg max-w-none prose-headings:font-bold prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl prose-a:text-blue-600 prose-a:no-underline hover:prose-a:underline prose-strong:text-gray-900 prose-code:bg-gray-100 prose-code:px-1 prose-code:rounded prose-pre:bg-gray-900 prose-pre:text-gray-100">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {markdownContent}
            </ReactMarkdown>
          </article>
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-gray-500 text-sm">
          <p>
            This report was generated by an AI research agent. While we strive for accuracy,
            please verify critical information with official sources before making decisions.
          </p>
        </div>
      </div>
    </div>
  );
}
